apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:aJYqR1DhlQX5EOo7Q9QtIcvTNF31UPdV86JTz626zFqzPfJf,iv:bP6OAxZ6oxGkLzZcGUWpKZVXXxMVH2dp9UPTI7tJQ54=,tag:LHHPGHc1aKo3jMxr/AOCAA==,type:str]
    TUNNEL_TOKEN: ""
    credentials.json: ENC[AES256_GCM,data:U9ZV5bibFlP3042pchHINOkrzzUbb1GYiRw3WbhGdgo4mpp/rD+Chgb9+x3bG0MS/lDIR9Vz73V2XjWwusmgA24J+VPF0EmTBWIkjeKui0DofIQu8YQ9E+yS1IERxMr+yhKOASN76tothrMPAsC0KvZnZwIYNO1J4g7K4gmJthZYljTmpBScudpg8M2G/OfFC7pvTbrWm+IiqAvGfFPCDxIkcDRtODP5i/DcmF77bA==,iv:kA7KBCH3JO6poNzfIkrAyzLnY8njwQnO4GspwWOG70o=,tag:P0D6ra2+lFy0uNEa4eqnIw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19t2rqvh4g93j6ry2rq2tqg8rm88h0tfx2vjuqxm9fr2vk6p5g50qjqnaht
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrSlo0N3BVaDBmTi8yaXZL
            ZzZLTVk4Szh1ZzljMENGWW1tS05IblFtQ1VvClpxNnVXQkhhZHVlN0Rsb3B1YmNu
            TFR1WWY3N2Y5Q2MwQUJST08xczdSUE0KLS0tIG1lOUcwbGVZVkR6ajVpKzFQdHBG
            dVBZcU1maVhxbG43QUVEd25IVU5DNkkKpD2uz5ExDOoEd0XAt8jg3w0vqNP2Ghr7
            wFOKU4hCWzf9Fe7kKWixPUcFfcRxXOX5by+JskSSyyqEGP5Z635eSg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-09T19:49:37Z"
    mac: ENC[AES256_GCM,data:n44z4bLSWWJ0ZcgmL/GEerTXwVtTq8d0dGRPrEoZgqfhXGtfrih3yqVC8sAhw+y6S3YybO3RKUPGIzP7LESuTbCfb7kb6HvdIGkKebfkxYwvky4915ltCjc3Os1o0iinqqUH7L22vrf9oorMPv6tT0S/tN+/HB/1KtCi3hqGrcM=,iv:ZZJHDjtuhPSQ6jIwSs1fdimVjFAGqxl5P5Wa8PR5xig=,tag:aTgH76Iz0y/bKHEAWeCnFQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
