apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:kcA2whOkEMp/b53/DoI2hfzLuuSUVPXlJjkKsP7uXiGLbN+k,iv:oVfY3499Ov8cg9tilUA7b0ev8BNYjwRdMngWpL97M5g=,tag:aFKEAYp82G0nYRw07ESNpg==,type:str]
    TUNNEL_TOKEN: ""
    credentials.json: ENC[AES256_GCM,data:bq6P7qZNMlqS7WDFWPj5o68cbpeUAm3+OpcKB11bFeorjYBmbfpduYPcVy6PnEJtVpT9SgaSuMQnNty0OBeT081M3X9DYupbQk//Q7cwmUNgINlT3aeRjQNVIhf8T7z4WA5rjU32Su4brKeRtDMoKGftUahYDrtK20hMce12KqrjW6YrIgUezYLfukYJaTyqDs8N0xmgiJXVu8m/NB/chbCvSKTnl0KnJlHHks91iQ==,iv:4bLWxjsCUMPjb/Up7ftSfE1sa1dsWQLry8+Xyc62Qhc=,tag:BhDmt9oa43qJLdGBuY0r7A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19t2rqvh4g93j6ry2rq2tqg8rm88h0tfx2vjuqxm9fr2vk6p5g50qjqnaht
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqSTE1SXJxNU5JZFZrRlE4
            VmV2bUthekhuWnc3U3JWdFRSU2h5R29tWkZNClNXb21VM0R5YXdTa2hiQkNiK1F4
            Qmh1QTRNL3paZXlpV1R5cWc3OGlQUWMKLS0tIFo4TkkwZDVWYjAyRmpCSHZXMit5
            YmREZ2RoU2ZTdHJXRUkxOEtxRUdHQ3cKyc6fMEVzOX8fQGK1Y17iPqC/RnsF59/S
            QL2G2fnKpLJvo06pdDfOKZ+Zp0b/LH57GWC8O5vs/ikdCz5a8DFKnA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-29T14:07:04Z"
    mac: ENC[AES256_GCM,data:V2vERVSDB4T8N+oerdengAYCpKCbPEad/eMFRnKUsE6/cdTB6urTsxVlxmfy0z8Wjx1qkrgqDAXvXVolFVopoDlfQy8T/Tyzd9i5WETgtdnLHgO+R7zSlE1bJ0qybFKyJz0ghVjxy7+oVApGHfnOG5JasWEZUVMVW9qFZsSuHvk=,iv:lfkjpJRTL98N+h8RzvDOQvKTbBfh1/NpPeo1s5sBWw8=,tag:MuY80vYn9Cv6ii2ro+AeOw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
