apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:ZmFxO6i9bgO4da0HSkB75CWeBDsg9YP7cHSahvBJHIb5t2zqX1cIyMGvn/MZv9yqxR4Rdz0kH/fkRfHidd7Oi/6bx9EOLHQKc4b1eGiHe/WNgRFUfjmsGdnIBmJ3pQ==,iv:/F593+FnHp299IaWRX0gwgMMcPkVwp3ArOJ0ANsFq50=,tag:IQg2QcMfBOygNNhZTSUxWQ==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:UatRkrKx772X4pFu,iv:gg9I2HijMOJi0LPSwzJkSGWd6Y+QYKeOZaZvI7J5dJs=,tag:x4RcTGabpeXjvaI14DFuvQ==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:eQG0KfuKSHa36WWyvyQaG1EFZurW6zwK,iv:693HviyCc0Ujmh85YlslE1fiDzeMDBUim3ZaYTxJF48=,tag:CG2xDpMpMSaB84PyoeP7MA==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:XMWByr+lU3qBC4OShNDVcJGRx1rKlusmGg4EJ/WWI+svpRjz,iv:Gs/K3yElEWUA/FdxrVFSeG473QTuBmr0tWJKWuIcBiw=,tag:onpD05KBArOWMhP6U009pg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19t2rqvh4g93j6ry2rq2tqg8rm88h0tfx2vjuqxm9fr2vk6p5g50qjqnaht
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMdk16RWtJc2VNTDdCL3U5
            NFNOdnFtVmh1bVQxbVNUVStrSUtaRmpnNlc4CnNSaWRTUkl0R3lHR1RKWTJpVTJB
            YWhoQ0hNaTBXbkhZOHppZTZPb1RYdHMKLS0tIDRVakJ1WUZ3aURURXhtaDZSTzBo
            QldSMW5DNFVQVllQNkphUVZGbENkSmsKu/B8PzfmAV1J15VX8n10inSsvwIKzJuF
            HGFgyFn7I5tB+5R1FTHDr8Z8vR3jBigfizODGpLhbLc/0RyeQ0kRYQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-09T19:49:37Z"
    mac: ENC[AES256_GCM,data:Aw6uH6o4SMKdCG3D7JOG5hNSJbdvLjxfLr3erOvMAxk4AuJnmEaAMTMqZsFGRO9rv4FMti2LODcEzYW+jcYlKbFQ80QgEEH2DFQjAhekVYz0xpApuytEKJBTBtjWdmylzFaOvbaHZ1lV0CDTVy9I3KFeecjkf5c2AClWgn0HDKg=,iv:XVox8s3pqhJ4y8pEMd4L+TC+wL266tju1Rv8zYCSKUY=,tag:BwbmtYvi65rR5BcKmEdeqQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
